server:
  port: 8081
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fifa?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    mapper-locations: classpath:/mapper/**/*.xml
    password: 'zkwndk12!@'
    username: fifa
